[package]
name = "futures_codec"
edition = "2018"
version = "0.3.0"
authors = ["Matt Hunzinger <matthunz2@gmail.com>"]
description = "Utilities for encoding and decoding frames using `async/await`"
license = "MIT"
readme = "README.md"
repository = "https://github.com/matthunz/futures-codec"
homepage = "https://github.com/matthunz/futures-codec"
documentation = "https://docs.rs/crate/futures_codec"
keywords = ["future", "futures", "async", "codec"]
categories = ["asynchronous", "network-programming"]

[dependencies]
futures-preview = "0.3.0-alpha.17"
memchr = "2.2.1"
byte-pool = { path = "../byte-pool" }
buf_redux = "0.8.4"
